---
- name: Add rook-release chart repo
  community.kubernetes.helm_repository:
    state: present
    name: rook-release
    repo_url: "https://charts.rook.io/release"

- name: Deploy rook-ceph
  community.kubernetes.helm:
    state: "{{ ceph_state }}"
    name: rook-ceph
    namespace: "{{ namespace }}"
    create_namespace: true
    chart_version: "{{ rook_version }}"
    chart_ref: rook-release/rook-ceph
    values: "{{ lookup('template', 'rook-ceph-values.yaml.j2') | from_yaml | combine(ceph_chart_values, recursive=True) }}"
    wait: "{{ wait }}"

- name: Deploy rook-ceph-cluster
  community.kubernetes.helm:
    state: "{{ ceph_state }}"
    name: rook-ceph-cluster
    namespace: "{{ namespace }}"
    create_namespace: true
    chart_version: "{{ rook_version }}"
    chart_ref: rook-release/rook-ceph-cluster
    values: "{{ lookup('template', 'rook-ceph-cluster-values.yaml.j2') | from_yaml | combine(ceph_cluster_chart_values, recursive=True) }}"
    wait: "{{ wait }}"

- name: Check ceph status
  shell: kubectl -n {{ namespace }} exec -i deploy/rook-ceph-tools -- ceph status 
  register: ceph_status
  until: ceph_status.rc == 0 and 'HEALTH_OK' in ceph_status.stdout
  delay: 180
  retries: 10
  when: wait

# - name: debug
#   debug:
#     var: ceph_status